site_name: Schach in Welzheim
site_url: https://schachwelzheim.github.io/schachwelzheim/
site_description: Schachaktivitäten in Welzheim, im Verein, in Schulen, ...
site_author: Schach in Welzheim

# Design & Theme
theme:
  name: material
  features:
    - navigation.instant
  language: de
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: green

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: green

# Eigenes CSS
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
  - tags:
      tags_file: aktuelles/aktuelles-tags.md

# Markdown
markdown_extensions:
  - attr_list
  - pymdownx.snippets
